spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/las_vegas?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    port: 15672
    exchange: register.exchange
    queue: register.queue
    routingkey: register.routingkey

application:
  title: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'

logging:
  level:
    root: INFO

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always